### ISSUE TITLE
Arrow & WASD Controls not working in normal mode

### ISSUE THREAD

**Issue by Miv2nir** [Starpelly/Mododger#1]
Basically what the title says, normally one can use the WASD & Arrow Keys to have clean control over the player on specific sections of a map (especially on challenges) but apparently that doesn't seem to work yet (FPS mode disabled).

**Comment by Starpelly** [comment]
god dammit

**Comment by Starpelly** [comment]
fixed https://github.com/Starpelly/Mododger/commit/80dc40fd752764a232d4bfe1d5620762c04d4ebe
